# Generated by Django 5.1.6 on 2025-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_disease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
